import type { EntryLogBoardColors, EntryLogBoardLabels, LogEntry } from './types'

export const DEFAULT_LABELS: Required<EntryLogBoardLabels> = {
  title: '入退室ログ',
  join: 'in',
  leave: 'out',
}

export const DEFAULT_COLORS: Required<EntryLogBoardColors> = {
  background: '#3c3b36',
  header: '#5246a5',
  title: '#ffffff',
  timestamp: '#c3c3c3',
  text: '#f5f5f5',
  join: '#32c671',
  leave: '#828282',
}

export const DEFAULT_PLACEHOLDER_ENTRIES: LogEntry[] = [
  // {
  //   id: 'sample-join-1',
  //   userId: 'sample-1',
  //   displayName: 'Alice',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:00:01',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-2',
  //   userId: 'sample-2',
  //   displayName: 'Bob',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:01:02',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-3',
  //   userId: 'sample-3',
  //   displayName: 'Carol',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:02:03',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-leave-1',
  //   userId: 'sample-2',
  //   displayName: 'Bob',
  //   type: 'leave',
  //   timestamp: '2026-01-01 12:03:04',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-4',
  //   userId: 'sample-4',
  //   displayName: 'Dave',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:04:05',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-5',
  //   userId: 'sample-5',
  //   displayName: 'Eve',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:05:06',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-6',
  //   userId: 'sample-6',
  //   displayName: 'Frank',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:06:07',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-leave-2',
  //   userId: 'sample-1',
  //   displayName: 'Alice',
  //   type: 'leave',
  //   timestamp: '2026-01-01 12:07:08',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-7',
  //   userId: 'sample-7',
  //   displayName: 'Grace',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:08:09',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-8',
  //   userId: 'sample-8',
  //   displayName: 'Heidi',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:09:10',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-9',
  //   userId: 'sample-9',
  //   displayName: 'Ivan',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:10:11',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-leave-3',
  //   userId: 'sample-4',
  //   displayName: 'Dave',
  //   type: 'leave',
  //   timestamp: '2026-01-01 12:11:12',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-10',
  //   userId: 'sample-10',
  //   displayName: 'Judy',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:12:13',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-11',
  //   userId: 'sample-11',
  //   displayName: 'Ken',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:13:14',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-12',
  //   userId: 'sample-12',
  //   displayName: 'Liam',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:14:15',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-leave-4',
  //   userId: 'sample-3',
  //   displayName: 'Carol',
  //   type: 'leave',
  //   timestamp: '2026-01-01 12:15:16',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-13',
  //   userId: 'sample-13',
  //   displayName: 'Mia',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:16:17',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-14',
  //   userId: 'sample-14',
  //   displayName: 'Noah',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:17:18',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-15',
  //   userId: 'sample-15',
  //   displayName: 'Olivia',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:18:19',
  //   avatarUrl: null,
  // },
  // {
  //   id: 'sample-join-16',
  //   userId: 'sample-16',
  //   displayName: 'Peggy',
  //   type: 'join',
  //   timestamp: '2026-01-01 12:19:20',
  //   avatarUrl: null,
  // },
]
